class StaticText {
  static const String
  aboutmeTitle = "About Me",
  aboutDescription =
      "Experienced Software Developer, who easily adapts to new technologies and procedures with enthusiasm. A team player, yet also works well on own initiative. Meticulous, with strong knowledge in information technology, computer applications, database management and programming. Possesses a Bachelor of Science in Computer Information Systems from the Northern Caribbean University, Jamaica. \n I’m very hard working person and after each of my projects I can say that I’ve learn’t something new. That for me is a plus where I can provide someone with new functional technology and walk away with more knowledge. \n My field is not only about working and to have the title. I enjoy what I do and I enjoy finding solutions to problems. I can proudly say I’ve seen my progress from beginner to where I am, and for that I am very proud.\n\n Key Skills\n –Custom Api integration with Advanced Querying\n – Deeplinking on both platforms\n – State Management (Riverpods, Bloc)\n – MVC approach\n – OOP \n – Database – Mongodb,firebase,SQL \n – Push Notifications – Firebase, OneSignal \n – Programming Languages – Node Js (TypeScript), Dart, Laravel \n - Agile Development – SCRUM Architectural Pattern – MVC \n - OOP \n - File Storage and Access \n - Websockets \n - Responsive clean UI",
  adfireDescription =
      "An advertisement mobile application. This app was designed to be used in Bahamas as requested to promote and advertise Ads such as jobs, properties for sale or rent, sales and trending news. This App was built using: Flutter, MongoDb ,Node Js(Typescript), One signal push notifications, Google storage bucket, Amazon Web Services (AWS) Key technologies used in this app were: Push notifications for both Platforms, Deep linking for both platforms, WebSocket, File Storage and Access, Custom API with Advanced Querying, Responsive clean UI etc, This application also ensures that only an admin (Owner of the application can perform required tasks.",
  rescueDescription =
      "A mobile application that was designed to be used in Jamaica. This app was designed to help people who are in need of assistance. Users of this application can state their issues they want assistance with. Purchase accessories like car batteries, tires etc. One of my favourite feature is the ability to purchase fuel or for electric cars to get a top up if either runs out of juice anywhere in the country.\n This app was built using: Flutter, MongoDb ,Node Js(Typescript), One signal push notifications, Google storage bucket, Amazon Web Services (AWS) Key technologies used in this app were: Push notifications for both Platforms, Deep linking for both platforms, WebSocket, File Storage and Access, Custom API with Advanced Querying, Responsive clean UI etc. this application consisted of three difference side: 1. Admin, 2. User, 3. Assistant",
  transportDescription =
      "Transport, this is a mobile application made with flutter and Laravel. The idea behind this application was to get better and play around with social sign in such as facebook or google. Users could sign in and request different size trucks to pick up anything (Lumber, House Equipments etc) and deliver it to a prescribed location.",
  fosterHomeDescription =
      "Fosters Home Office, this mobile application was made using flutter and firebase. This allowed for a user to be able to sign in a reserve a doctor’s appointment. View finances (Money possibly owed to the company). Lastly, purchase medication through the application and provide a digital prescription to show pharmacists.",
  ncuDescription =
      "This was one of the first application I made using flutter. This was a simple application that allowed students to view their grades and also view their timetable. This was made using flutter and firebase.",
  uluMeDescription =
      "UluMe is a mobile application that was made using flutter and firebase. This application is a chat application which users can send each other messages.";
}
